version: "2.3"
services:
  # Nginx server
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/config:/etc/nginx
      - ./nginx/log/:/var/log/nginx/
      - ../static/:/opt/apps/static/
    command: /tmp/run_nginx.sh
    environment:
      - DOLLAR=$$
    env_file:
      - ./.env
    depends_on:
      - django
    restart: always

  # Django server
  django:
    build:
      context: ../
      dockerfile: docker/django/Dockerfile
    expose:
      - ${DJANGO_PORT}
    volumes:
      - ../src:/src
      - ../logs:/logs
      - ../static:/static
      - ../media:/media
      - ../database:/database
      - ../docker/.env:/docker/.env
    command: bash -c "cd src &&
                      python manage.py collectstatic --noinput &&
                      python manage.py migrate &&
                      gunicorn --bind 0.0.0.0:${DJANGO_PORT} core.wsgi --reload"
    restart: always
networks:
  default:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network
